AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'log/**/*'
    - 'Gemfile'
    - 'spec/support/**/*'
    # TODO Must be big refactor
    - 'config/initializers/gems/*'
    - 'app/controllers/comments_controller.rb'
    - 'app/uploaders/audio_uploader.rb'
    - 'app/controllers/messages_controller.rb'
    - 'app/controllers/beats_controller.rb'
    - 'app/controllers/concerns/beat_filters.rb'
Metrics/LineLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
